### PR TITLE
Urta's Quest - Typos

### PR DESCRIPTION
**Pull request by Frahuenheld**
By the way, the epilogue never plays if I tell Urta to go knock Edryn.

### CODE REVIEW

**Comment by Fenoxo** [comment]
Drop the second commit (the one with the god-child's dialogue). I intentionally didn't use quotations for his dialogue to help distinguish it from actual, normal talking.

**Comment by Frahuenheld** [comment]
Umm... how do I do that?

**Comment by Frahuenheld** [comment]
Done

**Comment by Frahuenheld** [comment]
Also, in UrtaPregs.as Line 2233 it says: "which should give Urta plenty of time for herself,"

I think it should be "which should give Lianna plenty of time for herself,"

**Pull request merged**
