### PR TITLE
A variety of patches

### PR DESCRIPTION
**Pull request by IndirectOne**
Fixes for issues #685, #686, #689, #690, #691 

Also changed a bunch of old code (mostly in masturbation.as) that used dogDescript, horseDescript, etc. to generate text for the player's cock(s). This allows a lot of functions in Appearance.as and descriptors.as to be stripped out or simplified.

### CODE REVIEW

**Comment by IndirectOne** [comment]
Found and removed a lot of old functions which were no longer used anywhere. Moved almost all code out of descriptors.as, putting it in Appearance, Creature or Utils.

Changed the lookup files for the parser so they use KGAMECLASS directly rather than accessing it through a void pointer. Now the compiler can give a warning if a function used by the parser is removed or moved.

**Comment by IndirectOne** [comment]
Added tmedwards' fix for my fix of Essrayle

**Comment by IndirectOne** [comment]
Fixes a bug reported in the forums - the item button did nothing in Lethice's stronghold.

**Comment by IndirectOne** [comment]
Fixes for #692, #695, #696

**Comment by IndirectOne** [comment]
Moved masturbation code out of the includes, now in classes/classes/Scenes/Masturbation.as.

Cut up corrupt Jojo's sex scenes and gave him a menu so the player can now decide how they want to have sex with him.

Cleaned up some code in Camp.as, making the menus a bit cleaner and removing several numbered calls to eventParser.

**Comment by IndirectOne** [comment]
Removed all the numbered references in the character creation classes and got rid of customCharCreation - all its code is now in CharCreation.as

**Comment by IndirectOne** [comment]
eventParser(1) replaced with playerMenu. All the numbered events are gone, replaced with direct calls to the appropriate functions. DoNext, doYesNo, simpleChoices and choices are now all typesafe.

**Comment by IndirectOne** [comment]
Fixes for issues #700, #701, #702 and #703.
Also a fixup for Helia's sex ambush.

**Comment by IndirectOne** [comment]
Fixes for #704, #705 and #707, plus a few more added to #703.

**Comment by IndirectOne** [comment]
Fixes for #699, #708 and #709, #711 and #712, plus a few more added to #703.

**Comment by IndirectOne** [comment]
Shouldn't have deleted those. Calls to doNext(playerMenu) after startCombat() were redundant, but these were direct calls to playerMenu(). They prevent an extra 'Next' button from appearing.

**Comment by IndirectOne** [comment]
Fixes for #715, #716, #717, #718, #719 and #721.

**Comment by Fenoxo** [comment]
I'm gonna merge this cause FUCK IT, but don't do huge overhauls to core systems that work fine. CoC doesn't really need performance improvements, and all you do is risk introducing pallets of new bugs.

**Pull request merged**
